#!/usr/bin/env bash
set -e

if ! [ -x "$(command -v brew)" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! [ -x "$(command -v ansible)" ]; then
  brew install ansible
fi

tags="$1"

if [ ! -d ~/.dotfiles/roles/${tags} ]; then
  echo "The specified tag (${tags}) doesn't exist!"
  exit 1
fi

if [ -z $tags ]; then
  tags="all"
fi

ANSIBLE_CONFIG=~/.dotfiles/ansible.cfg ansible-playbook -i ~/.dotfiles/hosts ~/.dotfiles/dotfiles.yml --vault-id @prompt --tags $tags

if command -v terminal-notifier 1>/dev/null 2>&1; then
  terminal-notifier -title "dotfiles: Bootstrap complete" -message "Successfully set up environment."
fi
